version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: acit-3855-docker.eastus.cloudapp.azure.com # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://acit-3855-docker.eastus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Handwoven-Faster1-Devourer-Yoyo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Vixen-Justifier-Elite8-Public'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  storage:
    image: storage:latest
    hostname: storage
    restart: unless-stopped
    ports:
      - "8090:8090"
    depends_on:
      - "db"
      - "kafka"
  receiver:
    image: receiver:latest
    hostname: receiver
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - storage
  processing:
    image: processing:latest
    hostname: processing
    restart: unless-stopped
    ports:
      - "8100:8100"
    network_mode: "host"
    depends_on:
      - storage
  audit_log:
    image: audit_log:latest
    hostname: audit_log
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - kafka

  # Names our volume
volumes:
  my-db:
